# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'politics-mod-main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1579, 819)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_2 = QtGui.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton = QtGui.QRadioButton(self.frame_2)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.horizontalLayout_30.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_17 = QtGui.QPushButton(self.frame_2)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.verticalLayout_2.addWidget(self.pushButton_17)
        self.lineEdit = QtGui.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox = QtGui.QCheckBox(self.frame_2)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout.addWidget(self.checkBox)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setFrameShape(QtGui.QFrame.Box)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_30.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.tableWidget_2 = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidget_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16016006, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.frame_4 = QtGui.QFrame(self.tab)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_21 = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.horizontalLayout_2.addWidget(self.pushButton_21)
        self.pushButton_28 = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.horizontalLayout_2.addWidget(self.pushButton_28)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_19 = QtGui.QPushButton(self.frame_4)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.horizontalLayout_3.addWidget(self.pushButton_19)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_2 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setTextFormat(QtCore.Qt.LogText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_16.addWidget(self.label_2)
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_16.addWidget(self.lineEdit_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setFrameShape(QtGui.QFrame.Box)
        self.label_4.setTextFormat(QtCore.Qt.LogText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_18.addWidget(self.label_4)
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_18.addWidget(self.lineEdit_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.gridLayout_7.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setFrameShape(QtGui.QFrame.Box)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_28.addWidget(self.label_9)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_28.addWidget(self.lineEdit_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setFrameShape(QtGui.QFrame.Box)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_29.addWidget(self.label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_29.addWidget(self.lineEdit_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_29)
        self.gridLayout_7.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_4)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_10 = QtGui.QPushButton(self.frame)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.pushButton_9 = QtGui.QPushButton(self.frame)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_6 = QtGui.QPushButton(self.frame)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_8.addWidget(self.pushButton_6)
        self.pushButton_5 = QtGui.QPushButton(self.frame)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_8 = QtGui.QPushButton(self.frame)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_9.addWidget(self.pushButton_8)
        self.pushButton_7 = QtGui.QPushButton(self.frame)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_9.addWidget(self.pushButton_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_12 = QtGui.QPushButton(self.frame)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_10.addWidget(self.pushButton_12)
        self.pushButton_11 = QtGui.QPushButton(self.frame)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_10.addWidget(self.pushButton_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pushButton_13 = QtGui.QPushButton(self.frame)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_11.addWidget(self.pushButton_13)
        self.pushButton_16 = QtGui.QPushButton(self.frame)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_11.addWidget(self.pushButton_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.lineEdit_3 = QtGui.QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_6.addWidget(self.lineEdit_3)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.textEdit_2 = QtGui.QTextEdit(self.frame)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_3.addWidget(self.textEdit_2, 2, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.frame)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_3.addWidget(self.lineEdit_5, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_18 = QtGui.QPushButton(self.frame)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.horizontalLayout_4.addWidget(self.pushButton_18)
        self.pushButton_20 = QtGui.QPushButton(self.frame)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.horizontalLayout_4.addWidget(self.pushButton_20)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_14.addWidget(self.frame)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setFrameShape(QtGui.QFrame.Box)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_23.addWidget(self.label_5)
        self.lineEdit_12 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_23.addWidget(self.lineEdit_12)
        self.gridLayout_6.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.frame_3)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_6.addWidget(self.pushButton_14, 3, 0, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setFrameShape(QtGui.QFrame.Box)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_12.addWidget(self.label_7)
        self.lineEdit_14 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setPlaceholderText(_fromUtf8(""))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_12.addWidget(self.lineEdit_14)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pushButton_15 = QtGui.QPushButton(self.frame_3)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_13.addWidget(self.pushButton_15)
        self.pushButton_31 = QtGui.QPushButton(self.frame_3)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.horizontalLayout_13.addWidget(self.pushButton_31)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.line = QtGui.QFrame(self.frame_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_15.addWidget(self.line)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.pushButton_29 = QtGui.QPushButton(self.frame_3)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.horizontalLayout_26.addWidget(self.pushButton_29)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_26.addWidget(self.label)
        self.spinBox = QtGui.QSpinBox(self.frame_3)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_26.addWidget(self.spinBox)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.verticalLayout_15.addLayout(self.horizontalLayout_25)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setFrameShape(QtGui.QFrame.Box)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_19.addWidget(self.label_8)
        self.comboBox = QtGui.QComboBox(self.frame_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_19.addWidget(self.comboBox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_14.addWidget(self.lineEdit_4)
        self.textEdit_3 = QtGui.QTextEdit(self.frame_3)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.verticalLayout_14.addWidget(self.textEdit_3)
        self.gridLayout_6.addLayout(self.verticalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_27.addWidget(self.checkBox_2)
        self.lineEdit_15 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_15.setReadOnly(False)
        self.lineEdit_15.setPlaceholderText(_fromUtf8(""))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_27.addWidget(self.lineEdit_15)
        self.gridLayout_6.addLayout(self.horizontalLayout_27, 2, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.tab)
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.webView = QtWebKit.QWebView(self.frame_6)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayout_9.addWidget(self.webView, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_7 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.webView_2 = QtWebKit.QWebView(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView_2.sizePolicy().hasHeightForWidth())
        self.webView_2.setSizePolicy(sizePolicy)
        self.webView_2.setMaximumSize(QtCore.QSize(900, 16777215))
        self.webView_2.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView_2.setObjectName(_fromUtf8("webView_2"))
        self.gridLayout_10.addWidget(self.webView_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_7, 0, 1, 1, 1)
        self.frame_5 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.lineEdit_18 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.verticalLayout_11.addWidget(self.lineEdit_18)
        self.pushButton_33 = QtGui.QPushButton(self.frame_5)
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.verticalLayout_11.addWidget(self.pushButton_33)
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout_11.addWidget(self.lineEdit_9)
        self.textEdit = QtGui.QTextEdit(self.frame_5)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_11.addWidget(self.textEdit)
        self.pushButton_24 = QtGui.QPushButton(self.frame_5)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.verticalLayout_11.addWidget(self.pushButton_24)
        self.textEdit_5 = QtGui.QTextEdit(self.frame_5)
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.verticalLayout_11.addWidget(self.textEdit_5)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.pushButton_25 = QtGui.QPushButton(self.frame_5)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.horizontalLayout_22.addWidget(self.pushButton_25)
        self.pushButton_26 = QtGui.QPushButton(self.frame_5)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.horizontalLayout_22.addWidget(self.pushButton_26)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.pushButton_27 = QtGui.QPushButton(self.frame_5)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.verticalLayout_12.addWidget(self.pushButton_27)
        self.lineEdit_11 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.verticalLayout_12.addWidget(self.lineEdit_11)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.tableWidget_4 = QtGui.QTableWidget(self.frame_5)
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_18.addWidget(self.tableWidget_4)
        self.frame_9 = QtGui.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtGui.QFrame.Box)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.checkBox_4 = QtGui.QCheckBox(self.frame_9)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_36.addWidget(self.checkBox_4)
        self.lineEdit_19 = QtGui.QLineEdit(self.frame_9)
        self.lineEdit_19.setReadOnly(False)
        self.lineEdit_19.setPlaceholderText(_fromUtf8(""))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_36.addWidget(self.lineEdit_19)
        self.gridLayout_13.addLayout(self.horizontalLayout_36, 2, 0, 1, 1)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_14 = QtGui.QLabel(self.frame_9)
        self.label_14.setFrameShape(QtGui.QFrame.Box)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_37.addWidget(self.label_14)
        self.lineEdit_20 = QtGui.QLineEdit(self.frame_9)
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setPlaceholderText(_fromUtf8(""))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.horizontalLayout_37.addWidget(self.lineEdit_20)
        self.verticalLayout_20.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.pushButton_34 = QtGui.QPushButton(self.frame_9)
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.horizontalLayout_38.addWidget(self.pushButton_34)
        self.pushButton_35 = QtGui.QPushButton(self.frame_9)
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.horizontalLayout_38.addWidget(self.pushButton_35)
        self.verticalLayout_20.addLayout(self.horizontalLayout_38)
        self.line_3 = QtGui.QFrame(self.frame_9)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_20.addWidget(self.line_3)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.pushButton_36 = QtGui.QPushButton(self.frame_9)
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.horizontalLayout_40.addWidget(self.pushButton_36)
        self.label_15 = QtGui.QLabel(self.frame_9)
        self.label_15.setFrameShape(QtGui.QFrame.Box)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_40.addWidget(self.label_15)
        self.spinBox_3 = QtGui.QSpinBox(self.frame_9)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_40.addWidget(self.spinBox_3)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_40)
        self.verticalLayout_20.addLayout(self.horizontalLayout_39)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_16 = QtGui.QLabel(self.frame_9)
        self.label_16.setFrameShape(QtGui.QFrame.Box)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_41.addWidget(self.label_16)
        self.comboBox_3 = QtGui.QComboBox(self.frame_9)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_41.addWidget(self.comboBox_3)
        self.verticalLayout_19.addLayout(self.horizontalLayout_41)
        self.lineEdit_21 = QtGui.QLineEdit(self.frame_9)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.verticalLayout_19.addWidget(self.lineEdit_21)
        self.textEdit_6 = QtGui.QTextEdit(self.frame_9)
        self.textEdit_6.setObjectName(_fromUtf8("textEdit_6"))
        self.verticalLayout_19.addWidget(self.textEdit_6)
        self.gridLayout_13.addLayout(self.verticalLayout_19, 1, 0, 1, 1)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_17 = QtGui.QLabel(self.frame_9)
        self.label_17.setFrameShape(QtGui.QFrame.Box)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_42.addWidget(self.label_17)
        self.lineEdit_22 = QtGui.QLineEdit(self.frame_9)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.horizontalLayout_42.addWidget(self.lineEdit_22)
        self.gridLayout_13.addLayout(self.horizontalLayout_42, 0, 0, 1, 1)
        self.pushButton_37 = QtGui.QPushButton(self.frame_9)
        self.pushButton_37.setObjectName(_fromUtf8("pushButton_37"))
        self.gridLayout_13.addWidget(self.pushButton_37, 3, 0, 1, 1)
        self.verticalLayout_18.addWidget(self.frame_9)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.verticalLayout_18.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_21.addLayout(self.verticalLayout_18)
        self.gridLayout_12.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1579, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.radioButton.setText(_translate("MainWindow", "Submissions only", None))
        self.radioButton_2.setText(_translate("MainWindow", "Comments only", None))
        self.radioButton_3.setText(_translate("MainWindow", "Both", None))
        self.pushButton_17.setText(_translate("MainWindow", "Refresh", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "filter (comma-separated)", None))
        self.checkBox.setText(_translate("MainWindow", "Feed mode", None))
        self.label_11.setText(_translate("MainWindow", "Queue size: 0", None))
        self.tableWidget_2.setSortingEnabled(True)
        self.pushButton_21.setText(_translate("MainWindow", "Open link", None))
        self.pushButton_28.setText(_translate("MainWindow", "Open post", None))
        self.pushButton_19.setText(_translate("MainWindow", "Check for reposts", None))
        self.label_2.setText(_translate("MainWindow", "Domain", None))
        self.label_4.setText(_translate("MainWindow", "Date", None))
        self.label_9.setText(_translate("MainWindow", "Submission title", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Title from submission", None))
        self.label_10.setText(_translate("MainWindow", "Article title", None))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Title from article", None))
        self.pushButton.setText(_translate("MainWindow", "Remove (RC)", None))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Hello", None))
        self.pushButton_2.setText(_translate("MainWindow", "Remove (RBT)", None))
        self.pushButton_4.setText(_translate("MainWindow", "Remove (OOD)", None))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Hello", None))
        self.pushButton_3.setText(_translate("MainWindow", "Remove (OT)", None))
        self.pushButton_10.setText(_translate("MainWindow", "Remove (404)", None))
        self.pushButton_9.setToolTip(_translate("MainWindow", "Hello", None))
        self.pushButton_9.setText(_translate("MainWindow", "Remove (PW)", None))
        self.pushButton_6.setText(_translate("MainWindow", "Remove (NSU)", None))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Hello", None))
        self.pushButton_5.setText(_translate("MainWindow", "Remove (NS)", None))
        self.pushButton_8.setText(_translate("MainWindow", "Remove (AS)", None))
        self.pushButton_7.setToolTip(_translate("MainWindow", "Hello", None))
        self.pushButton_7.setText(_translate("MainWindow", "Remove (PB/V)", None))
        self.pushButton_12.setText(_translate("MainWindow", "Remove (NA/V/SC)", None))
        self.pushButton_11.setToolTip(_translate("MainWindow", "Hello", None))
        self.pushButton_11.setText(_translate("MainWindow", "Remove (Custom)", None))
        self.pushButton_13.setText(_translate("MainWindow", "Approve", None))
        self.pushButton_16.setText(_translate("MainWindow", "Report", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Report reason", None))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Megathread permalink", None))
        self.pushButton_18.setText(_translate("MainWindow", "Remove (point to megathread)", None))
        self.pushButton_20.setText(_translate("MainWindow", "Remove (no reason)", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Report", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count", None))
        self.label_5.setText(_translate("MainWindow", "Author", None))
        self.pushButton_14.setText(_translate("MainWindow", "Execute ban", None))
        self.label_7.setText(_translate("MainWindow", "Latest usernote", None))
        self.pushButton_15.setText(_translate("MainWindow", "View user profile", None))
        self.pushButton_31.setText(_translate("MainWindow", "Check submission ratio", None))
        self.pushButton_29.setText(_translate("MainWindow", "Calculate ban length/note", None))
        self.label.setText(_translate("MainWindow", "Ban length", None))
        self.label_8.setText(_translate("MainWindow", "Preset", None))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Ban note", None))
        self.checkBox_2.setText(_translate("MainWindow", "Add usernote", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Submission", None))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "Highlight text (comma-separated)", None))
        self.pushButton_33.setText(_translate("MainWindow", "Open comment and context in browser", None))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Title from submission", None))
        self.pushButton_24.setText(_translate("MainWindow", "Fetch parent comment", None))
        self.pushButton_25.setText(_translate("MainWindow", "Approve", None))
        self.pushButton_26.setText(_translate("MainWindow", "Remove", None))
        self.pushButton_27.setText(_translate("MainWindow", "Report", None))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Report reason", None))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Report", None))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count", None))
        self.checkBox_4.setText(_translate("MainWindow", "Add usernote", None))
        self.label_14.setText(_translate("MainWindow", "Latest usernote", None))
        self.pushButton_34.setText(_translate("MainWindow", "View user profile", None))
        self.pushButton_35.setText(_translate("MainWindow", "Check submission ratio", None))
        self.pushButton_36.setText(_translate("MainWindow", "Calculate ban length/note", None))
        self.label_15.setText(_translate("MainWindow", "Ban length", None))
        self.label_16.setText(_translate("MainWindow", "Preset", None))
        self.lineEdit_21.setPlaceholderText(_translate("MainWindow", "Ban note", None))
        self.label_17.setText(_translate("MainWindow", "Author", None))
        self.pushButton_37.setText(_translate("MainWindow", "Execute ban", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Comment", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

